// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: evaluate.proto

package social_api_ws

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 评论
type CmdEveluate int32

const (
	CmdEveluate_CmdEveluateEveluateReq  CmdEveluate = 0
	CmdEveluate_CmdEveluateEveluateResp CmdEveluate = 1
)

// Enum value maps for CmdEveluate.
var (
	CmdEveluate_name = map[int32]string{
		0: "CmdEveluateEveluateReq",
		1: "CmdEveluateEveluateResp",
	}
	CmdEveluate_value = map[string]int32{
		"CmdEveluateEveluateReq":  0,
		"CmdEveluateEveluateResp": 1,
	}
)

func (x CmdEveluate) Enum() *CmdEveluate {
	p := new(CmdEveluate)
	*p = x
	return p
}

func (x CmdEveluate) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdEveluate) Descriptor() protoreflect.EnumDescriptor {
	return file_evaluate_proto_enumTypes[0].Descriptor()
}

func (CmdEveluate) Type() protoreflect.EnumType {
	return &file_evaluate_proto_enumTypes[0]
}

func (x CmdEveluate) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdEveluate.Descriptor instead.
func (CmdEveluate) EnumDescriptor() ([]byte, []int) {
	return file_evaluate_proto_rawDescGZIP(), []int{0}
}

// 评价请求
type EveluateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//分数
	Score uint64 `protobuf:"varint,1,opt,name=score,proto3" json:"score,omitempty"`
	//印象tag, '-' 分割开
	Tags string `protobuf:"bytes,2,opt,name=tags,proto3" json:"tags,omitempty"`
	//主播id
	AnchorId uint64 `protobuf:"varint,3,opt,name=anchor_id,json=anchorId,proto3" json:"anchor_id,omitempty"`
	//订单id
	OrderId uint64 `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
}

func (x *EveluateReq) Reset() {
	*x = EveluateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EveluateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EveluateReq) ProtoMessage() {}

func (x *EveluateReq) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EveluateReq.ProtoReflect.Descriptor instead.
func (*EveluateReq) Descriptor() ([]byte, []int) {
	return file_evaluate_proto_rawDescGZIP(), []int{0}
}

func (x *EveluateReq) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *EveluateReq) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *EveluateReq) GetAnchorId() uint64 {
	if x != nil {
		return x.AnchorId
	}
	return 0
}

func (x *EveluateReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// 评论返回
type EveluateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suc bool `protobuf:"varint,1,opt,name=suc,proto3" json:"suc,omitempty"`
}

func (x *EveluateResp) Reset() {
	*x = EveluateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_evaluate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EveluateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EveluateResp) ProtoMessage() {}

func (x *EveluateResp) ProtoReflect() protoreflect.Message {
	mi := &file_evaluate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EveluateResp.ProtoReflect.Descriptor instead.
func (*EveluateResp) Descriptor() ([]byte, []int) {
	return file_evaluate_proto_rawDescGZIP(), []int{1}
}

func (x *EveluateResp) GetSuc() bool {
	if x != nil {
		return x.Suc
	}
	return false
}

var File_evaluate_proto protoreflect.FileDescriptor

var file_evaluate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x65, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0d, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x77, 0x73, 0x22,
	0x6f, 0x0a, 0x0b, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x73,
	0x63, 0x6f, 0x72, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x6e, 0x63, 0x68,
	0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x61, 0x6e, 0x63,
	0x68, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x20, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x75, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73,
	0x75, 0x63, 0x2a, 0x46, 0x0a, 0x0b, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74,
	0x65, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65,
	0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x10, 0x00, 0x12, 0x1b, 0x0a,
	0x17, 0x43, 0x6d, 0x64, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x45, 0x76, 0x65, 0x6c,
	0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x10, 0x01, 0x32, 0x55, 0x0a, 0x08, 0x45, 0x76,
	0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x43, 0x61, 0x6c, 0x6c, 0x45, 0x76,
	0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x77, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x77, 0x73, 0x2e, 0x45, 0x76, 0x65, 0x6c, 0x75, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x42, 0x11, 0x5a, 0x0f, 0x2f, 0x3b, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x5f, 0x77, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_evaluate_proto_rawDescOnce sync.Once
	file_evaluate_proto_rawDescData = file_evaluate_proto_rawDesc
)

func file_evaluate_proto_rawDescGZIP() []byte {
	file_evaluate_proto_rawDescOnce.Do(func() {
		file_evaluate_proto_rawDescData = protoimpl.X.CompressGZIP(file_evaluate_proto_rawDescData)
	})
	return file_evaluate_proto_rawDescData
}

var file_evaluate_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_evaluate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_evaluate_proto_goTypes = []interface{}{
	(CmdEveluate)(0),     // 0: social.api.ws.CmdEveluate
	(*EveluateReq)(nil),  // 1: social.api.ws.EveluateReq
	(*EveluateResp)(nil), // 2: social.api.ws.EveluateResp
}
var file_evaluate_proto_depIdxs = []int32{
	1, // 0: social.api.ws.Eveluate.CallEveluate:input_type -> social.api.ws.EveluateReq
	2, // 1: social.api.ws.Eveluate.CallEveluate:output_type -> social.api.ws.EveluateResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_evaluate_proto_init() }
func file_evaluate_proto_init() {
	if File_evaluate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_evaluate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EveluateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_evaluate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EveluateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_evaluate_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluate_proto_goTypes,
		DependencyIndexes: file_evaluate_proto_depIdxs,
		EnumInfos:         file_evaluate_proto_enumTypes,
		MessageInfos:      file_evaluate_proto_msgTypes,
	}.Build()
	File_evaluate_proto = out.File
	file_evaluate_proto_rawDesc = nil
	file_evaluate_proto_goTypes = nil
	file_evaluate_proto_depIdxs = nil
}
