// Code generated by protoc-gen-go. DO NOT EDIT.
// source: wz.proto

package protopb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//OnlineList
type OnlineListReq struct {
	Nickname             string   `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OnlineListReq) Reset()         { *m = OnlineListReq{} }
func (m *OnlineListReq) String() string { return proto.CompactTextString(m) }
func (*OnlineListReq) ProtoMessage()    {}
func (*OnlineListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{0}
}

func (m *OnlineListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineListReq.Unmarshal(m, b)
}
func (m *OnlineListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineListReq.Marshal(b, m, deterministic)
}
func (m *OnlineListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineListReq.Merge(m, src)
}
func (m *OnlineListReq) XXX_Size() int {
	return xxx_messageInfo_OnlineListReq.Size(m)
}
func (m *OnlineListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineListReq.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineListReq proto.InternalMessageInfo

func (m *OnlineListReq) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type OnlineListResp struct {
	UserList             []*UserInfo `protobuf:"bytes,1,rep,name=user_list,json=userList,proto3" json:"user_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *OnlineListResp) Reset()         { *m = OnlineListResp{} }
func (m *OnlineListResp) String() string { return proto.CompactTextString(m) }
func (*OnlineListResp) ProtoMessage()    {}
func (*OnlineListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{1}
}

func (m *OnlineListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OnlineListResp.Unmarshal(m, b)
}
func (m *OnlineListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OnlineListResp.Marshal(b, m, deterministic)
}
func (m *OnlineListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OnlineListResp.Merge(m, src)
}
func (m *OnlineListResp) XXX_Size() int {
	return xxx_messageInfo_OnlineListResp.Size(m)
}
func (m *OnlineListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OnlineListResp.DiscardUnknown(m)
}

var xxx_messageInfo_OnlineListResp proto.InternalMessageInfo

func (m *OnlineListResp) GetUserList() []*UserInfo {
	if m != nil {
		return m.UserList
	}
	return nil
}

//ApplyVs
type ApplyVsReq struct {
	TargetUserId         uint64   `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyVsReq) Reset()         { *m = ApplyVsReq{} }
func (m *ApplyVsReq) String() string { return proto.CompactTextString(m) }
func (*ApplyVsReq) ProtoMessage()    {}
func (*ApplyVsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{2}
}

func (m *ApplyVsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyVsReq.Unmarshal(m, b)
}
func (m *ApplyVsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyVsReq.Marshal(b, m, deterministic)
}
func (m *ApplyVsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyVsReq.Merge(m, src)
}
func (m *ApplyVsReq) XXX_Size() int {
	return xxx_messageInfo_ApplyVsReq.Size(m)
}
func (m *ApplyVsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyVsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyVsReq proto.InternalMessageInfo

func (m *ApplyVsReq) GetTargetUserId() uint64 {
	if m != nil {
		return m.TargetUserId
	}
	return 0
}

type ApplyVsResp struct {
	UserInfo             *UserInfo `protobuf:"bytes,1,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	TargetUserInfo       *UserInfo `protobuf:"bytes,2,opt,name=target_user_info,json=targetUserInfo,proto3" json:"target_user_info,omitempty"`
	Status               uint32    `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Room                 uint64    `protobuf:"varint,4,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ApplyVsResp) Reset()         { *m = ApplyVsResp{} }
func (m *ApplyVsResp) String() string { return proto.CompactTextString(m) }
func (*ApplyVsResp) ProtoMessage()    {}
func (*ApplyVsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{3}
}

func (m *ApplyVsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyVsResp.Unmarshal(m, b)
}
func (m *ApplyVsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyVsResp.Marshal(b, m, deterministic)
}
func (m *ApplyVsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyVsResp.Merge(m, src)
}
func (m *ApplyVsResp) XXX_Size() int {
	return xxx_messageInfo_ApplyVsResp.Size(m)
}
func (m *ApplyVsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyVsResp.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyVsResp proto.InternalMessageInfo

func (m *ApplyVsResp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *ApplyVsResp) GetTargetUserInfo() *UserInfo {
	if m != nil {
		return m.TargetUserInfo
	}
	return nil
}

func (m *ApplyVsResp) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ApplyVsResp) GetRoom() uint64 {
	if m != nil {
		return m.Room
	}
	return 0
}

//VsResp
type VsRespReq struct {
	Room                 uint64   `protobuf:"varint,1,opt,name=room,proto3" json:"room,omitempty"`
	Action               uint32   `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VsRespReq) Reset()         { *m = VsRespReq{} }
func (m *VsRespReq) String() string { return proto.CompactTextString(m) }
func (*VsRespReq) ProtoMessage()    {}
func (*VsRespReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{4}
}

func (m *VsRespReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VsRespReq.Unmarshal(m, b)
}
func (m *VsRespReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VsRespReq.Marshal(b, m, deterministic)
}
func (m *VsRespReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VsRespReq.Merge(m, src)
}
func (m *VsRespReq) XXX_Size() int {
	return xxx_messageInfo_VsRespReq.Size(m)
}
func (m *VsRespReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VsRespReq.DiscardUnknown(m)
}

var xxx_messageInfo_VsRespReq proto.InternalMessageInfo

func (m *VsRespReq) GetRoom() uint64 {
	if m != nil {
		return m.Room
	}
	return 0
}

func (m *VsRespReq) GetAction() uint32 {
	if m != nil {
		return m.Action
	}
	return 0
}

type VsRespResp struct {
	IsSuccess            uint32   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VsRespResp) Reset()         { *m = VsRespResp{} }
func (m *VsRespResp) String() string { return proto.CompactTextString(m) }
func (*VsRespResp) ProtoMessage()    {}
func (*VsRespResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{5}
}

func (m *VsRespResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VsRespResp.Unmarshal(m, b)
}
func (m *VsRespResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VsRespResp.Marshal(b, m, deterministic)
}
func (m *VsRespResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VsRespResp.Merge(m, src)
}
func (m *VsRespResp) XXX_Size() int {
	return xxx_messageInfo_VsRespResp.Size(m)
}
func (m *VsRespResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VsRespResp.DiscardUnknown(m)
}

var xxx_messageInfo_VsRespResp proto.InternalMessageInfo

func (m *VsRespResp) GetIsSuccess() uint32 {
	if m != nil {
		return m.IsSuccess
	}
	return 0
}

//Chess
type ChessReq struct {
	Room                 uint64   `protobuf:"varint,1,opt,name=room,proto3" json:"room,omitempty"`
	UserId               uint64   `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	X                    int32    `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChessReq) Reset()         { *m = ChessReq{} }
func (m *ChessReq) String() string { return proto.CompactTextString(m) }
func (*ChessReq) ProtoMessage()    {}
func (*ChessReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{6}
}

func (m *ChessReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChessReq.Unmarshal(m, b)
}
func (m *ChessReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChessReq.Marshal(b, m, deterministic)
}
func (m *ChessReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChessReq.Merge(m, src)
}
func (m *ChessReq) XXX_Size() int {
	return xxx_messageInfo_ChessReq.Size(m)
}
func (m *ChessReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ChessReq.DiscardUnknown(m)
}

var xxx_messageInfo_ChessReq proto.InternalMessageInfo

func (m *ChessReq) GetRoom() uint64 {
	if m != nil {
		return m.Room
	}
	return 0
}

func (m *ChessReq) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ChessReq) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *ChessReq) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type ChessResp struct {
	IsWin                bool     `protobuf:"varint,1,opt,name=is_win,json=isWin,proto3" json:"is_win,omitempty"`
	Color                int32    `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChessResp) Reset()         { *m = ChessResp{} }
func (m *ChessResp) String() string { return proto.CompactTextString(m) }
func (*ChessResp) ProtoMessage()    {}
func (*ChessResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{7}
}

func (m *ChessResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChessResp.Unmarshal(m, b)
}
func (m *ChessResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChessResp.Marshal(b, m, deterministic)
}
func (m *ChessResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChessResp.Merge(m, src)
}
func (m *ChessResp) XXX_Size() int {
	return xxx_messageInfo_ChessResp.Size(m)
}
func (m *ChessResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ChessResp.DiscardUnknown(m)
}

var xxx_messageInfo_ChessResp proto.InternalMessageInfo

func (m *ChessResp) GetIsWin() bool {
	if m != nil {
		return m.IsWin
	}
	return false
}

func (m *ChessResp) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

//Surrender
type SurrenderReq struct {
	TargetUserId         string   `protobuf:"bytes,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurrenderReq) Reset()         { *m = SurrenderReq{} }
func (m *SurrenderReq) String() string { return proto.CompactTextString(m) }
func (*SurrenderReq) ProtoMessage()    {}
func (*SurrenderReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{8}
}

func (m *SurrenderReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurrenderReq.Unmarshal(m, b)
}
func (m *SurrenderReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurrenderReq.Marshal(b, m, deterministic)
}
func (m *SurrenderReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurrenderReq.Merge(m, src)
}
func (m *SurrenderReq) XXX_Size() int {
	return xxx_messageInfo_SurrenderReq.Size(m)
}
func (m *SurrenderReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SurrenderReq.DiscardUnknown(m)
}

var xxx_messageInfo_SurrenderReq proto.InternalMessageInfo

func (m *SurrenderReq) GetTargetUserId() string {
	if m != nil {
		return m.TargetUserId
	}
	return ""
}

type SurrenderResp struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SurrenderResp) Reset()         { *m = SurrenderResp{} }
func (m *SurrenderResp) String() string { return proto.CompactTextString(m) }
func (*SurrenderResp) ProtoMessage()    {}
func (*SurrenderResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{9}
}

func (m *SurrenderResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SurrenderResp.Unmarshal(m, b)
}
func (m *SurrenderResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SurrenderResp.Marshal(b, m, deterministic)
}
func (m *SurrenderResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurrenderResp.Merge(m, src)
}
func (m *SurrenderResp) XXX_Size() int {
	return xxx_messageInfo_SurrenderResp.Size(m)
}
func (m *SurrenderResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SurrenderResp.DiscardUnknown(m)
}

var xxx_messageInfo_SurrenderResp proto.InternalMessageInfo

func (m *SurrenderResp) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

//
type UserInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Sex                  int64    `protobuf:"varint,4,opt,name=Sex,proto3" json:"Sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_727c207b9f43e6c4, []int{10}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func init() {
	proto.RegisterType((*OnlineListReq)(nil), "protopb.OnlineListReq")
	proto.RegisterType((*OnlineListResp)(nil), "protopb.OnlineListResp")
	proto.RegisterType((*ApplyVsReq)(nil), "protopb.ApplyVsReq")
	proto.RegisterType((*ApplyVsResp)(nil), "protopb.ApplyVsResp")
	proto.RegisterType((*VsRespReq)(nil), "protopb.VsRespReq")
	proto.RegisterType((*VsRespResp)(nil), "protopb.VsRespResp")
	proto.RegisterType((*ChessReq)(nil), "protopb.ChessReq")
	proto.RegisterType((*ChessResp)(nil), "protopb.ChessResp")
	proto.RegisterType((*SurrenderReq)(nil), "protopb.SurrenderReq")
	proto.RegisterType((*SurrenderResp)(nil), "protopb.SurrenderResp")
	proto.RegisterType((*UserInfo)(nil), "protopb.UserInfo")
}

func init() { proto.RegisterFile("wz.proto", fileDescriptor_727c207b9f43e6c4) }

var fileDescriptor_727c207b9f43e6c4 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0x65, 0xd2, 0xa6, 0x9b, 0xdc, 0x6d, 0xca, 0x3a, 0xac, 0x5a, 0x04, 0xa1, 0x0c, 0x82, 0x85,
	0x85, 0x08, 0xab, 0xa0, 0xb0, 0x2f, 0xae, 0x3e, 0x09, 0x82, 0x30, 0x45, 0x05, 0x5f, 0x6a, 0x36,
	0x99, 0xd5, 0xc1, 0xee, 0x4c, 0x9c, 0x3b, 0xb5, 0xad, 0x3f, 0xc8, 0xdf, 0x29, 0x73, 0x93, 0xd6,
	0x54, 0xc8, 0xd3, 0xdc, 0x33, 0xdc, 0x73, 0xce, 0xfd, 0x82, 0x64, 0xf3, 0x3b, 0xaf, 0x9d, 0xf5,
	0x96, 0x9f, 0xd0, 0x53, 0xdf, 0x88, 0x0b, 0xc8, 0x3e, 0x98, 0x95, 0x36, 0xea, 0xbd, 0x46, 0x2f,
	0xd5, 0x4f, 0xfe, 0x08, 0x12, 0xa3, 0xcb, 0x1f, 0xa6, 0xb8, 0x53, 0x53, 0x36, 0x63, 0xf3, 0x54,
	0x1e, 0xb0, 0x78, 0x0d, 0x93, 0x6e, 0x32, 0xd6, 0x3c, 0x87, 0x74, 0x8d, 0xca, 0x2d, 0x57, 0x1a,
	0xfd, 0x94, 0xcd, 0x06, 0xf3, 0xd3, 0xcb, 0x7b, 0x79, 0xab, 0x9d, 0x7f, 0x44, 0xe5, 0xde, 0x99,
	0x5b, 0x2b, 0x93, 0x90, 0x13, 0x38, 0xe2, 0x12, 0xe0, 0xba, 0xae, 0x57, 0xbb, 0x4f, 0x18, 0xbc,
	0x9e, 0xc0, 0xc4, 0x17, 0xee, 0x9b, 0xf2, 0x4b, 0x12, 0xd1, 0x15, 0x39, 0x0e, 0xe5, 0xb8, 0xf9,
	0x25, 0x7e, 0x25, 0xfe, 0x30, 0x38, 0x3d, 0x90, 0x3a, 0x9e, 0xda, 0xdc, 0x5a, 0x22, 0xf4, 0x7b,
	0x86, 0x88, 0x5f, 0xc1, 0xd9, 0x91, 0x4b, 0xa0, 0x45, 0x7d, 0xb4, 0x49, 0xc7, 0x3a, 0x90, 0x1f,
	0xc0, 0x08, 0x7d, 0xe1, 0xd7, 0x38, 0x1d, 0xcc, 0xd8, 0x3c, 0x93, 0x2d, 0xe2, 0x1c, 0x86, 0xce,
	0xda, 0xbb, 0xe9, 0x90, 0x0a, 0xa6, 0x58, 0xbc, 0x84, 0xb4, 0x29, 0x31, 0xf4, 0xb6, 0x4f, 0x60,
	0xff, 0x12, 0x82, 0x58, 0x51, 0x7a, 0x6d, 0x0d, 0xf9, 0x67, 0xb2, 0x45, 0xe2, 0x02, 0x60, 0x4f,
	0xc4, 0x9a, 0x3f, 0x06, 0xd0, 0xb8, 0xc4, 0x75, 0x59, 0x2a, 0x44, 0xe2, 0x67, 0x32, 0xd5, 0xb8,
	0x68, 0x3e, 0xc4, 0x02, 0x92, 0xb7, 0xdf, 0x15, 0x62, 0x9f, 0xc9, 0x43, 0x38, 0xd9, 0x4f, 0x33,
	0xa2, 0xef, 0x11, 0x4d, 0xa2, 0xe2, 0x63, 0x60, 0x5b, 0xea, 0x22, 0x96, 0x6c, 0x1b, 0xd0, 0x8e,
	0xaa, 0x8f, 0x25, 0xdb, 0x89, 0x57, 0x90, 0xb6, 0xa2, 0x58, 0xf3, 0xfb, 0x30, 0xd2, 0xb8, 0xdc,
	0x68, 0x43, 0xba, 0x89, 0x8c, 0x35, 0x7e, 0xd6, 0x86, 0x9f, 0x43, 0x5c, 0xda, 0x95, 0x75, 0x24,
	0x1b, 0xcb, 0x06, 0x88, 0x17, 0x30, 0x5e, 0xac, 0x9d, 0x53, 0xa6, 0x52, 0xae, 0x7f, 0xa7, 0xe9,
	0x7f, 0x3b, 0x7d, 0x0a, 0x59, 0x87, 0x85, 0x75, 0x67, 0xce, 0x8d, 0x67, 0x8b, 0xc4, 0x57, 0x48,
	0x0e, 0xbb, 0x98, 0x40, 0x74, 0x38, 0x91, 0x48, 0x57, 0x47, 0xa7, 0x1a, 0x1d, 0x9f, 0x6a, 0xd0,
	0xbb, 0xfe, 0x55, 0xf8, 0xc2, 0x51, 0xc7, 0xa9, 0x6c, 0x11, 0x3f, 0x83, 0xc1, 0x42, 0x6d, 0xa9,
	0xf1, 0x81, 0x0c, 0xe1, 0x9b, 0xf3, 0x2f, 0x3c, 0xcf, 0x9f, 0xb5, 0x87, 0x70, 0xd5, 0xbe, 0x37,
	0x23, 0x0a, 0x9e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xee, 0x4d, 0xca, 0x57, 0x33, 0x03, 0x00,
	0x00,
}
